# Generated by Django 4.1.3 on 2022-11-21 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Label', models.CharField(choices=[('None', 'Select Label'), ('Personal', 'Personal'), ('Work', 'Work'), ('Family', 'Family'), ('Holiday', 'Holiday'), ('Other', 'Other')], default='None', max_length=10)),
                ('StartDateTime', models.DateTimeField()),
                ('EndDateTime', models.DateTimeField()),
                ('WholeDay', models.BooleanField(default=False)),
                ('EventURL', models.URLField(blank=True)),
                ('Guests', models.CharField(max_length=100)),
                ('Location', models.CharField(blank=True, max_length=100)),
                ('Description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
