# Generated by Django 4.1.3 on 2022-11-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Guests',
        ),
    ]
