# Generated by Django 4.1.3 on 2022-11-22 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventApp', '0003_event_eventguests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventGuests',
            field=models.ManyToManyField(blank=True, related_name='EventGuests_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
