# Generated by Django 4.1.3 on 2022-11-24 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventApp', '0004_alter_event_eventguests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventGuests',
        ),
        migrations.AddField(
            model_name='event',
            name='EventGuests',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='EventGuests', to=settings.AUTH_USER_MODEL),
        ),
    ]
