# Generated by Django 4.1.3 on 2022-11-24 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventApp', '0006_remove_event_eventguests_event_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Guests',
            field=models.ManyToManyField(blank=True, related_name='Guests_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
