# Generated by Django 4.1.3 on 2022-12-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='TaskCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
