# Generated by Django 4.1.3 on 2022-12-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_todo_comment_todo_taskcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Important',
            field=models.BooleanField(default=False),
        ),
    ]
