# Generated by Django 4.1.3 on 2023-02-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0004_todo_supervisorimportant_alter_todo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='SupervisorImportant',
        ),
    ]
