# Generated by Django 4.1.3 on 2022-12-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='Draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='Important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='Read',
            field=models.BooleanField(default=False),
        ),
    ]
