# Generated by Django 4.1.3 on 2022-12-28 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmailApp', '0002_email_deleted_email_draft_email_important_email_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='BlindCarbonCopy',
            field=models.ManyToManyField(related_name='blindcarboncopy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='CarbonCopy',
            field=models.ManyToManyField(related_name='carboncopy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='Label',
            field=models.CharField(choices=[('None', 'None'), ('Personal', 'Personal'), ('Important', 'Important'), ('Private', 'Private'), ('Company', 'Company')], default='None', max_length=10),
        ),
    ]
