# Generated by Django 4.1.3 on 2023-01-02 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmailApp', '0003_email_blindcarboncopy_email_carboncopy_email_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='BlindCarbonCopy',
            field=models.ManyToManyField(blank=True, related_name='blindcarboncopy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='CarbonCopy',
            field=models.ManyToManyField(blank=True, related_name='carboncopy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='Draft',
            field=models.BooleanField(),
        ),
    ]
