# Generated by Django 4.1.3 on 2023-01-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0011_alter_email_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='BlindCarbonCopy',
            new_name='Bcc',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='BlindCarbonCopyDelete',
            new_name='BccDelete',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='BlindCarbonCopyDraft',
            new_name='BccImportant',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='BlindCarbonCopyLabel',
            new_name='BccLabel',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='BlindCarbonCopyImportant',
            new_name='BccRead',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='BlindCarbonCopyRead',
            new_name='BccTrash',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='CarbonCopy',
            new_name='Cc',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='BlindCarbonCopyTrash',
            new_name='CcDelete',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='CarbonCopyDelete',
            new_name='CcImportant',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='CarbonCopyLabel',
            new_name='CcLabel',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='CarbonCopyDraft',
            new_name='CcRead',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='CarbonCopyImportant',
            new_name='CcTrash',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='CarbonCopyRead',
            new_name='Draft',
        ),
        migrations.RemoveField(
            model_name='email',
            name='CarbonCopyTrash',
        ),
        migrations.RemoveField(
            model_name='email',
            name='ReceiverDraft',
        ),
        migrations.RemoveField(
            model_name='email',
            name='SenderDraft',
        ),
        migrations.AddField(
            model_name='email',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
