# Generated by Django 4.1.3 on 2023-01-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp', '0016_remove_email_receiver_email_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='Body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='Subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
