# Generated by Django 4.1.3 on 2022-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_traininginfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
    ]
