# Generated by Django 4.1.3 on 2022-11-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_personalinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardandscholarshipinfo',
            old_name='AwardingBody',
            new_name='Organization',
        ),
    ]
