# Generated by Django 4.1.3 on 2022-11-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_academicinfo_id_alter_academicinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Faculty',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Gender',
            field=models.CharField(choices=[(0, 'Select Gender'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0, max_length=15),
        ),
    ]
