# Generated by Django 4.1.3 on 2022-11-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_remove_personalinfo_faculty_personalinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Gender',
            field=models.CharField(choices=[('0', 'Select Gender'), ('1', 'Male')], default=0, max_length=15),
        ),
    ]
