# Generated by Django 4.1.3 on 2022-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_alter_personalinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='BloodGroup',
            field=models.CharField(choices=[('0', 'Select Blood Group'), ('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'AB+'), ('6', 'AB-'), ('7', 'O+'), ('8', 'O-')], default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='DateOfBirth',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='MaritalStatus',
            field=models.CharField(choices=[('0', 'Select Marital Status'), ('1', 'Single'), ('2', 'Married'), ('3', 'Divorced'), ('4', 'Widowed')], default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Nationality',
            field=models.CharField(default='Bangladeshi', max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Religion',
            field=models.CharField(choices=[('0', 'Select Religion'), ('1', 'Islam'), ('2', 'Hinduism'), ('3', 'Buddhism'), ('4', 'Christianity')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Gender',
            field=models.CharField(choices=[('0', 'Select Gender'), ('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default=0, max_length=15),
        ),
    ]
