# Generated by Django 4.1.3 on 2022-11-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_personalinfo_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='NIDNumber',
            field=models.CharField(default='00000000000000000', max_length=17),
        ),
    ]
