# Generated by Django 4.1.3 on 2022-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_personalinfo_nidnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='NIDNumber',
            field=models.CharField(max_length=17),
        ),
    ]
