# Generated by Django 4.1.3 on 2022-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_alter_personalinfo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='ProfilePic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
