# Generated by Django 4.1.3 on 2022-11-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_personalinfo_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Department',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Designation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='EmployeeID',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='NIDNumber',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Nationality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='PermanentAddress',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='PresentAddress',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
