# Generated by Django 4.1.3 on 2022-12-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0022_remove_personalinfo_id_personalinfo_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='LastName',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
