# Generated by Django 4.1.3 on 2022-12-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0023_remove_personalinfo_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
    ]
