# Generated by Django 4.1.3 on 2022-12-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0025_teachinginfo_credit_teachinginfo_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachinginfo',
            name='CourseCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teachinginfo',
            name='CourseTitle',
            field=models.CharField(max_length=50),
        ),
    ]
