# Generated by Django 4.1.3 on 2023-01-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0026_alter_teachinginfo_coursecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Phone',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
