# Generated by Django 4.1.3 on 2023-01-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0027_alter_personalinfo_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='Institute',
            field=models.CharField(max_length=200),
        ),
    ]
