# Generated by Django 4.1.3 on 2023-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0028_alter_academicinfo_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='Degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='Major',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='Designation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='Organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='EmployeeID',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='PermanentAddress',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='PresentAddress',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AlterField(
            model_name='publicationinfo',
            name='Journal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationinfo',
            name='Title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teachinginfo',
            name='CourseCode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachinginfo',
            name='CourseTitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='traininginfo',
            name='Duration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='traininginfo',
            name='Institute',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='traininginfo',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
