# Generated by Django 4.1.3 on 2023-01-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0029_alter_academicinfo_degree_alter_academicinfo_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='CGPA',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
